# Generated by Django 5.1.7 on 2025-03-25 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='SelfieHistorica',
        ),
    ]
