# Generated by Django 5.1.7 on 2025-03-25 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0002_rename_produto_selfiehistorica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfiehistorica',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='thumbs/'),
        ),
    ]
