# Generated by Django 5.1.7 on 2025-03-30 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0003_alter_selfiehistorica_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfiehistorica',
            name='personagemSelfie',
            field=models.ImageField(blank=True, null=True, upload_to='personagemSelfie'),
        ),
    ]
