# Generated by Django 5.1.7 on 2025-04-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0004_selfiehistorica_personagemselfie'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioDescricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='audios/')),
            ],
        ),
    ]
