# Generated by Django 5.1.7 on 2025-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0005_audiodescricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='exposicoes/', verbose_name='Imagem')),
                ('video_url', models.CharField(blank=True, max_length=50, null=True, verbose_name='ID do Vídeo do YouTube')),
            ],
            options={
                'verbose_name': 'Exposição',
                'verbose_name_plural': 'Exposições',
            },
        ),
    ]
