# Generated by Django 5.1.7 on 2025-06-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0006_exposicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposicao',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=5, verbose_name='Tipo de Mídia'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='imagem',
            field=models.ImageField(blank=True, help_text="Envie uma imagem se selecionou 'Imagem' como tipo de mídia", null=True, upload_to='exposicoes/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='exposicao',
            name='video_url',
            field=models.CharField(blank=True, help_text="Insira apenas o ID do vídeo (ex: lETYY1fCXuE) se selecionou 'Vídeo' como tipo de mídia", max_length=50, null=True, verbose_name='ID do Vídeo do YouTube'),
        ),
    ]
