# Generated by Django 5.1.7 on 2025-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0007_exposicao_media_type_alter_exposicao_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicao',
            name='media_type',
            field=models.CharField(choices=[('imagem', 'Imagem'), ('video', 'Vídeo')], default='imagem', max_length=40, verbose_name='Tipo de Mídia'),
        ),
    ]
