# Generated by Django 5.1.7 on 2025-06-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ccmtj', '0008_alter_exposicao_media_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposicao',
            name='media_type',
            field=models.CharField(choices=[('image', 'Imagem'), ('video', 'Vídeo')], default='image', max_length=40, verbose_name='Tipo de Mídia'),
        ),
    ]
